export default {
  UPDATE: 'ui/UPDATE',
  RESET: 'ui/RESET',
  MODAL_SHOW: 'ui/MODAL_SHOW',
  MODAL_HIDE: 'ui/MODAL_HIDE',
  NOTIFICATION_SHOW: 'ui/NOTIFICATION_SHOW',
  NOTIFICATION_HIDE: 'ui/NOTIFICATION_HIDE',
};
